server:
  port: 9000

# DB연결 정보
datasource: 
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/datacore_v2_data_registry
  username: postgres
  password: postgres

  secondary: 
    use.yn: N
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/datacore_v2_data_registry
    username: postgres
    password: postgres
  
  hive: 
    use.yn: N
    driverClassName: org.apache.hive.jdbc.HiveDriver
    url: jdbc:hive2://203.253.128.181:10187/default
    username: hive
    password:
    baseDirPath: /user/hive/warehouse

  hbase:
    xmlPath: hbase-site.xml

data-federation:
  standalone: true
  csource:
    id:
    endpoint:
    regist-interval-millis:
    entity-infos:
    location:
  subscription:
    id:
    endpoint:
  data-registry:
    base-uri:
    sub-uri:
      csource:
      subscription: