CREATE SCHEMA DATACORE_USERTOOL
    AUTHORIZATION POSTGRES;


-- Schema of WIDGET_CHART_BASE table
CREATE TABLE DATACORE_USERTOOL.WIDGET_CHART_BASE
(
    WIDGET_ID		VARCHAR(36) NOT NULL,
    USER_ID			VARCHAR(32) NOT NULL,
    CHART_TYPE		VARCHAR(32) NOT NULL,
    CHART_ORDER		NUMERIC(5),
    CHART_SIZE		VARCHAR(100),
    DATA_TYPE		VARCHAR(10),
    CHART_TITLE		VARCHAR(32),
    CHART_X_NAME	VARCHAR(20),
    CHART_Y_NAME	VARCHAR(20),
    Y_AXIS_RANGE	VARCHAR(20),
    UPDATE_INTERVAL	NUMERIC(20),
    REALTIME_UPDATE_ENABLED	BOOLEAN DEFAULT FALSE,
    CHART_ATTRIBUTE	VARCHAR(100) NOT NULL,
    SEARCH_CONDITION	VARCHAR(1000),
    CREATE_DATETIME	TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    MODIFY_DATETIME	TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT WIDGET_CHART_BASE_PK PRIMARY KEY (WIDGET_ID, USER_ID)
);

-- 2022-01-27
DROP TABLE DATACORE_USERTOOL.WIDGET_CHART_BASE;

-- Schema of WIDGET_CHART_BASE table
CREATE TABLE DATACORE_USERTOOL.WIDGET_CHART_BASE
(
    WIDGET_ID		VARCHAR(36) NOT NULL,
    USER_ID			VARCHAR(32) NOT NULL,
    DASHBOARD_ID	VARCHAR(36) NOT NULL,
    CHART_TYPE		VARCHAR(32) NOT NULL,
    CHART_ORDER		NUMERIC(5),
    CHART_SIZE		VARCHAR(100),
    DATA_TYPE		VARCHAR(10),
    CHART_TITLE		VARCHAR(32),
    CHART_X_NAME	VARCHAR(20),
    CHART_Y_NAME	VARCHAR(20),
    Y_AXIS_RANGE	VARCHAR(20),
    UPDATE_INTERVAL	NUMERIC(20),
    REALTIME_UPDATE_ENABLED	BOOLEAN DEFAULT FALSE,
    CHART_ATTRIBUTE	VARCHAR(100) NOT NULL,
    SEARCH_CONDITION	VARCHAR(1000),
    MAP_SEARCH_CONDITION_ID	VARCHAR(36),
    FILE 			BYTEA,
    EXTENTION1		VARCHAR(100),
    EXTENTION2		VARCHAR(100),
    CREATE_DATETIME	TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    MODIFY_DATETIME	TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT WIDGET_CHART_BASE_PK PRIMARY KEY (WIDGET_ID, USER_ID, DASHBOARD_ID)
);

-- Schema of DASHBOARD_BASE table
CREATE TABLE DATACORE_USERTOOL.DASHBOARD_BASE
(
	DASHBOARD_ID	VARCHAR(36) NOT NULL,
	USER_ID			VARCHAR(32) NOT NULL,
	DASHBOARD_NAME	VARCHAR(32) NOT NULL,
	CREATE_DATETIME	TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    MODIFY_DATETIME	TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT DASHBOARD_BASE_PK PRIMARY KEY (DASHBOARD_ID, USER_ID)
);

-- Schema of MAP_SEARCH_CONDITION_BASE table
CREATE TABLE DATACORE_USERTOOL.MAP_SEARCH_CONDITION_BASE
(
	MAP_SEARCH_CONDITION_ID	VARCHAR(36) NOT NULL,
	MAP_SEARCH_CONDITION_TYPE	VARCHAR(10) NOT NULL,
	USER_ID					VARCHAR(32) NOT NULL,
	MAP_SEARCH_CONDITION_NAME	VARCHAR(32) NOT NULL,
	SEARCH_CONDITION		VARCHAR(2500),
	SUBSCRIPTION_CONDITION	VARCHAR(1000),
	CREATE_DATETIME	TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    MODIFY_DATETIME	TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT MAP_SEARCH_CONDITION_BASE_PK PRIMARY KEY (MAP_SEARCH_CONDITION_ID, MAP_SEARCH_CONDITION_TYPE, USER_ID)
);