CREATE SCHEMA DATA_MANAGER
    AUTHORIZATION POSTGRES;


CREATE TABLE DATA_MANAGER.DATA_MODEL_BASE
(
    ID		VARCHAR(1024),
    TYPE            VARCHAR(64) NOT NULL,
    TYPE_URI        VARCHAR(1024) NOT NULL,
    NAME	VARCHAR(100),
    DESCRIPTION     VARCHAR(500),
    DATA_MODEL      TEXT NOT NULL,
    ENABLED         BOOLEAN DEFAULT TRUE,
    CREATE_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID     VARCHAR(64),
    CONSTRAINT DATA_MODEL_BASE_PK PRIMARY KEY (ID),
    CONSTRAINT DATA_MODEL_BASE_UK01 UNIQUE (TYPE_URI)
);


-- 데이터 셋 테이블 스키마
CREATE TABLE DATA_MANAGER.DATASET_BASE
(
    ID                    VARCHAR(256) NOT NULL,
    NAME                  VARCHAR(256),
    DESCRIPTION           VARCHAR(512),
    UPDATE_INTERVAL       VARCHAR(50),
    CATEGORY              VARCHAR(4),
    PROVIDER_ORGANIZATION VARCHAR(256),
    PROVIDER_SYSTEM       VARCHAR(256),
    IS_PROCESSED          VARCHAR(256),
    OWNERSHIP             VARCHAR(32),
    KEYWORD               VARCHAR(4)[],
    LICENSE               VARCHAR(4),
    PROVIDING_API_URI     VARCHAR(512),
    RESTRICTIONS          VARCHAR(512),
    DATASET_EXTENSION     VARCHAR(16),
    DATASET_ITEMS         VARCHAR(512),
    TARGET_REGIONS        VARCHAR(512),
    SOURCE_DATASET_IDS    VARCHAR(512)[],
    DATA_STORE_URI        VARCHAR(1024)[],
    QUALITY_CHECK_ENABLED BOOLEAN,
    DATA_IDENTIFIER_TYPE  VARCHAR(64),
    DATAMODEL_ID        VARCHAR(1024),
    ENABLED               BOOLEAN      NOT NULL DEFAULT TRUE,
    STORAGE_RETENTION INTEGER,
    TOPIC_RETENTION BIGINT,
    CREATE_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID     VARCHAR(64),
    CONSTRAINT DATA_SET_BASE_PK PRIMARY KEY (ID)
);


-- Provision 서버 기본
CREATE TABLE DATA_MANAGER.PROVISION_SERVER_BASE
(
    ID                 VARCHAR(256)        NOT NULL,
    TYPE               VARCHAR(50)         NOT NULL,
    DESCRIPTION        VARCHAR(512),
    PROVISION_URI      VARCHAR(512)        NOT NULL,
    PROVISION_PROTOCOL VARCHAR(10)         NOT NULL,
    ENABLED            BOOLEAN DEFAULT 't' NOT NULL,
    PROVISION_ORDER    INTEGER   	   NOT NULL DEFAULT 1,
    CREATE_DATETIME    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID         VARCHAR(64),
    MODIFY_DATETIME    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID        VARCHAR(64),
    CONSTRAINT PROVISION_SERVER_BASE_PK PRIMARY KEY (ID)
);

-- 데이터 셋 흐름 기본
CREATE TABLE DATA_MANAGER.DATASET_FLOW_BASE
(
    DATASET_ID      VARCHAR(64)         NOT NULL,
    DESCRIPTION     VARCHAR(512),
    HISTORY_STORE_TYPE	VARCHAR(20)	NOT NULL,
    ENABLED         BOOLEAN DEFAULT 't' NOT NULL,
    CREATE_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID     VARCHAR(64),
    CONSTRAINT DATASET_FLOW_BASE_PK PRIMARY KEY (DATASET_ID)
);


-- 데이터 셋 흐름 서버 상세
CREATE TABLE DATA_MANAGER.DATASET_FLOW_SERVER_DETAIL
(
    DATASET_ID             VARCHAR(64)         NOT NULL,
    PROVISION_SERVER_TYPE  VARCHAR(50)         NOT NULL,
    BIG_DATA_STORAGE_TYPES VARCHAR(30),
    CONSTRAINT DATASET_FLOW_SERVER_DETAIL_PK PRIMARY KEY (DATASET_ID, PROVISION_SERVER_TYPE)
);



-- 2020-01-09
ALTER TABLE DATA_MANAGER.DATA_MODEL_BASE ADD COLUMN PROVISIONING_ID VARCHAR(64);
ALTER TABLE DATA_MANAGER.DATA_MODEL_BASE ADD COLUMN PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE;

ALTER TABLE DATA_MANAGER.DATASET_BASE ADD COLUMN PROVISIONING_ID VARCHAR(64);
ALTER TABLE DATA_MANAGER.DATASET_BASE ADD COLUMN PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE;
    
ALTER TABLE DATA_MANAGER.DATASET_FLOW_BASE ADD COLUMN PROVISIONING_ID VARCHAR(64);
ALTER TABLE DATA_MANAGER.DATASET_FLOW_BASE ADD COLUMN PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE;


-- 2020-03-19
ALTER TABLE DATA_MANAGER.DATASET_BASE ALTER COLUMN DATASET_EXTENSION TYPE VARCHAR(256);
ALTER TABLE DATA_MANAGER.DATASET_BASE ALTER COLUMN LICENSE TYPE VARCHAR(256);
ALTER TABLE DATA_MANAGER.DATASET_BASE ALTER COLUMN KEYWORD TYPE VARCHAR(256)[];
ALTER TABLE DATA_MANAGER.DATASET_BASE ALTER COLUMN CATEGORY TYPE VARCHAR(256);
ALTER TABLE DATA_MANAGER.DATASET_BASE ALTER COLUMN DATA_IDENTIFIER_TYPE TYPE VARCHAR(256);


-- 2021-07-04 접근제어(데이터셋) 관련
CREATE TABLE DATA_MANAGER.ACL_RULE
(
    ID                    VARCHAR(40) NOT NULL,
    USER_ID               VARCHAR(50),
    CLIENT_ID             VARCHAR(50),
    DATASET_ID            VARCHAR(256),
    CONDITION             VARCHAR(10) NOT NULL,
    CREATE_DATETIME       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID            VARCHAR(64),
    MODIFY_DATETIME       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID           VARCHAR(64),
    PROVISIONING_ID       VARCHAR(64),
    PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ACL_RULE_PKEY PRIMARY KEY (ID)
);
ALTER TABLE DATA_MANAGER.ACL_RULE RENAME COLUMN DATASET_ID TO RESOURCE_ID;
ALTER TABLE DATA_MANAGER.ACL_RULE ADD COLUMN RESOURCE_TYPE VARCHAR(10);

-- 2020-07-25
-- DATA_MODEL_BASE 테이블 DROP 후 신규 CREATE (PK 바뀜)
-- DATASET_BASE 테이블 DROP 후 신규 CREATE (데이터모델 PK 바뀜)

DROP TABLE DATA_MANAGER.DATASET_BASE;
DROP TABLE DATA_MANAGER.DATA_MODEL_BASE;

CREATE TABLE DATA_MANAGER.DATA_MODEL_BASE
(
    ID		VARCHAR(1024),
    TYPE            VARCHAR(64) NOT NULL,
    TYPE_URI        VARCHAR(1024) NOT NULL,
    NAME	VARCHAR(100),
    DESCRIPTION     VARCHAR(500),
    DATA_MODEL      TEXT NOT NULL,
    ENABLED         BOOLEAN DEFAULT TRUE,
    CREATE_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID     VARCHAR(64),
    PROVISIONING_ID	  VARCHAR(64),
    PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE,
    CONSTRAINT DATA_MODEL_BASE_PK PRIMARY KEY (ID),
    CONSTRAINT DATA_MODEL_BASE_UK01 UNIQUE (TYPE_URI)
);


-- 데이터 셋 테이블 스키마
CREATE TABLE DATA_MANAGER.DATASET_BASE
(
    ID                    VARCHAR(256) NOT NULL,
    NAME                  VARCHAR(256),
    DESCRIPTION           VARCHAR(512),
    UPDATE_INTERVAL       VARCHAR(50),
    CATEGORY              VARCHAR(256),
    PROVIDER_ORGANIZATION VARCHAR(256),
    PROVIDER_SYSTEM       VARCHAR(256),
    IS_PROCESSED          VARCHAR(256),
    OWNERSHIP             VARCHAR(32),
    KEYWORD               VARCHAR(256)[],
    LICENSE               VARCHAR(256),
    PROVIDING_API_URI     VARCHAR(512),
    RESTRICTIONS          VARCHAR(512),
    DATASET_EXTENSION     VARCHAR(256),
    DATASET_ITEMS         VARCHAR(512),
    TARGET_REGIONS        VARCHAR(512),
    SOURCE_DATASET_IDS    VARCHAR(512)[],
    DATA_STORE_URI        VARCHAR(1024)[],
    QUALITY_CHECK_ENABLED BOOLEAN,
    DATA_IDENTIFIER_TYPE  VARCHAR(256),
    DATAMODEL_ID        VARCHAR(1024),
    ENABLED               BOOLEAN      NOT NULL DEFAULT TRUE,
    STORAGE_RETENTION INTEGER,
    TOPIC_RETENTION BIGINT,
    CREATE_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID     VARCHAR(64),
    PROVISIONING_ID	  VARCHAR(64),
    PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE,
    CONSTRAINT DATA_SET_BASE_PK PRIMARY KEY (ID)
);

-- 2022-05-08
ALTER TABLE DATA_MANAGER.ACL_RULE ADD COLUMN OPERATION VARCHAR(16)[] DEFAULT '{"create", "update", "retrieve", "delete"}' NOT NULL;

-- 2022-06-11
ALTER TABLE DATA_MANAGER.ACL_RULE ALTER COLUMN CONDITION DROP NOT NULL;