CREATE SCHEMA INGEST_INTERFACE
    AUTHORIZATION POSTGRES;

-- 테이블 모델 테이블 스키마
CREATE TABLE INGEST_INTERFACE.DATA_MODEL_BASE
(
    NAMESPACE       VARCHAR(256),
    TYPE            VARCHAR(64),
    VERSION         VARCHAR(10),
    NAME            VARCHAR(100),
    DESCRIPTION     VARCHAR(500),
    DATA_MODEL      TEXT NOT NULL,
    ENABLED         BOOLEAN DEFAULT TRUE NOT NULL,
    CREATE_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID     VARCHAR(64),
    CONSTRAINT DATA_MODEL_BASE_PK PRIMARY KEY (NAMESPACE, TYPE, VERSION)
);

-- 데이터 셋 테이블 스키마
CREATE TABLE INGEST_INTERFACE.DATASET_BASE
(
    ID                    VARCHAR(256) NOT NULL,
    NAME                  VARCHAR(256),
    DESCRIPTION           VARCHAR(512),
    UPDATE_INTERVAL       VARCHAR(50),
    CATEGORY              VARCHAR(4),
    PROVIDER_ORGANIZATION VARCHAR(256),
    PROVIDER_SYSTEM       VARCHAR(256),
    IS_PROCESSED          VARCHAR(256),
    OWNERSHIP             VARCHAR(32),
    KEYWORD               VARCHAR(4)[],
    LICENSE               VARCHAR(4),
    PROVIDING_API_URI     VARCHAR(512),
    RESTRICTIONS          VARCHAR(512),
    DATASET_EXTENSION     VARCHAR(16),
    DATASET_ITEMS         VARCHAR(512),
    TARGET_REGIONS        VARCHAR(512),
    SOURCE_DATASET_IDS    VARCHAR(512)[],
    DATA_STORE_URI        VARCHAR(1024)[],
    QUALITY_CHECK_ENABLED BOOLEAN,
    DATA_IDENTIFIER_TYPE  VARCHAR(64),
    DATAMODEL_TYPE        VARCHAR(64),
    DATAMODEL_NAMESPACE   VARCHAR(256),
    DATAMODEL_VERSION     VARCHAR(10),
    ENABLED               BOOLEAN      NOT NULL DEFAULT TRUE,
    STORAGE_RETENTION INTEGER,
    TOPIC_RETENTION BIGINT,
    CREATE_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID     VARCHAR(64),
    CONSTRAINT DATA_SET_BASE_PK PRIMARY KEY (ID)
);




-- 품질 이력 테이블 스키마
CREATE TABLE INGEST_INTERFACE.VERIFICATION_HIST
(
    SEQ	BIGSERIAL  NOT NULL,
    IS_VERIFIED	BOOLEAN  NOT NULL,
    TEST_DATETIME	TIMESTAMP  NOT NULL,
    CREATE_DATETIME	TIMESTAMP  NOT NULL,
    DATASET_ID	VARCHAR(256)  NOT NULL,
    DATA_MODEL_TYPE	VARCHAR(64),
    DATA_MODEL_NAMESPACE	VARCHAR(256),
    DATA_MODEL_VERSION	VARCHAR(10),
    ENTITY_ID	VARCHAR(256),
    ERROR_CODE	VARCHAR(3),
    ERROR_CAUSE	VARCHAR(512),
    DATA	TEXT,
    CONSTRAINT VERIFICATION_HIST_PK PRIMARY KEY (SEQ)

);



-- 외부 플랫폼 인증 정보
CREATE TABLE INGEST_INTERFACE.EXTERNAL_PLATFORM_AUTHENTICATION_BASE
(
    ID	VARCHAR(256)  NOT NULL,
    NAME	VARCHAR(256)  NOT NULL,
    DESCRIPTION	VARCHAR(256) ,
    RECEPTION_IPS	VARCHAR(512)[]  NOT NULL,
    RECEPTION_DATASET_IDS	VARCHAR(512)[]  NOT NULL,
    DATA_INSTANCE_PREFIX	VARCHAR(64) ,
    RECEPTION_CLIENT_IDS	VARCHAR(512)[]  NOT NULL,
    CREATE_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID     VARCHAR(64),
    CONSTRAINT EXTERNAL_PLATFORM_AUTHENTICATION_BASE_PK PRIMARY KEY (ID)

);


-- 2020-01-09
ALTER TABLE INGEST_INTERFACE.DATA_MODEL_BASE ADD COLUMN PROVISIONING_ID VARCHAR(64);
ALTER TABLE INGEST_INTERFACE.DATA_MODEL_BASE ADD COLUMN PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE;

ALTER TABLE INGEST_INTERFACE.DATASET_BASE ADD COLUMN PROVISIONING_ID VARCHAR(64);
ALTER TABLE INGEST_INTERFACE.DATASET_BASE ADD COLUMN PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE;

-- 2020-03-19
ALTER TABLE INGEST_INTERFACE.DATASET_BASE ALTER COLUMN DATASET_EXTENSION TYPE VARCHAR(256);
ALTER TABLE INGEST_INTERFACE.DATASET_BASE ALTER COLUMN LICENSE TYPE VARCHAR(256);
ALTER TABLE INGEST_INTERFACE.DATASET_BASE ALTER COLUMN KEYWORD TYPE VARCHAR(256)[];
ALTER TABLE INGEST_INTERFACE.DATASET_BASE ALTER COLUMN CATEGORY TYPE VARCHAR(256);
ALTER TABLE INGEST_INTERFACE.DATASET_BASE ALTER COLUMN DATA_IDENTIFIER_TYPE TYPE VARCHAR(256);


-- 2021-07-03 접근제어
CREATE TABLE INGEST_INTERFACE.ACL_RULE
(
    ID                    VARCHAR(40) NOT NULL,
    USER_ID               VARCHAR(50),
    CLIENT_ID             VARCHAR(50),
    RESOURCE_ID            VARCHAR(256),
    RESOURCE_TYPE            VARCHAR(10),
    CONDITION             VARCHAR(10) NOT NULL,
    CREATE_DATETIME       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID            VARCHAR(64),
    MODIFY_DATETIME       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID           VARCHAR(64),
    PROVISIONING_ID       VARCHAR(64),
    PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ACL_RULE_PKEY PRIMARY KEY (ID)
);

-- 2021-07-20
-- DATA_MODEL_BASE 테이블 DROP 후 신규 CREATE (PK 바뀜)
-- DATASET_BASE 테이블 DROP 후 신규 CREATE (데이터모델 PK 바뀜)
-- VERIFICATION_HIST 테이블 DROP 후 신규 CREATE (데이터모델 PK 바뀜)

DROP TABLE INGEST_INTERFACE.DATASET_BASE;
DROP TABLE INGEST_INTERFACE.DATA_MODEL_BASE;
DROP TABLE INGEST_INTERFACE.VERIFICATION_HIST;

CREATE TABLE INGEST_INTERFACE.DATA_MODEL_BASE
(
    ID		    VARCHAR(1024),
    TYPE            VARCHAR(64) NOT NULL,
    TYPE_URI        VARCHAR(1024) NOT NULL,
    NAME            VARCHAR(100),
    DESCRIPTION     VARCHAR(500),
    DATA_MODEL      TEXT NOT NULL,
    ENABLED         BOOLEAN DEFAULT TRUE NOT NULL,
    CREATE_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID     VARCHAR(64),
    PROVISIONING_ID VARCHAR(64),
    PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE,
    CONSTRAINT DATA_MODEL_BASE_PK PRIMARY KEY (ID),
    CONSTRAINT DATA_MODEL_BASE_UK01 UNIQUE (TYPE_URI)
);

-- 데이터 셋 테이블 스키마
CREATE TABLE INGEST_INTERFACE.DATASET_BASE
(
    ID                    VARCHAR(256) NOT NULL,
    NAME                  VARCHAR(256),
    DESCRIPTION           VARCHAR(512),
    UPDATE_INTERVAL       VARCHAR(50),
    CATEGORY              VARCHAR(256),
    PROVIDER_ORGANIZATION VARCHAR(256),
    PROVIDER_SYSTEM       VARCHAR(256),
    IS_PROCESSED          VARCHAR(256),
    OWNERSHIP             VARCHAR(32),
    KEYWORD               VARCHAR(256)[],
    LICENSE               VARCHAR(256),
    PROVIDING_API_URI     VARCHAR(512),
    RESTRICTIONS          VARCHAR(512),
    DATASET_EXTENSION     VARCHAR(256),
    DATASET_ITEMS         VARCHAR(512),
    TARGET_REGIONS        VARCHAR(512),
    SOURCE_DATASET_IDS    VARCHAR(512)[],
    DATA_STORE_URI        VARCHAR(1024)[],
    QUALITY_CHECK_ENABLED BOOLEAN,
    DATA_IDENTIFIER_TYPE  VARCHAR(256),
    DATAMODEL_ID        VARCHAR(1024),
    ENABLED               BOOLEAN      NOT NULL DEFAULT TRUE,
    STORAGE_RETENTION INTEGER,
    TOPIC_RETENTION BIGINT,
    CREATE_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID     VARCHAR(64),
    PROVISIONING_ID VARCHAR(64),
    PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE,
    CONSTRAINT DATA_SET_BASE_PK PRIMARY KEY (ID)
);


-- 품질 이력 테이블 스키마
CREATE TABLE INGEST_INTERFACE.VERIFICATION_HIST
(
    SEQ	BIGSERIAL  NOT NULL,
    IS_VERIFIED	BOOLEAN  NOT NULL,
    TEST_DATETIME	TIMESTAMP  NOT NULL,
    CREATE_DATETIME	TIMESTAMP  NOT NULL,
    DATASET_ID	VARCHAR(256)  NOT NULL,
    DATA_MODEL_ID	VARCHAR(1024),
    ENTITY_ID	VARCHAR(256),
    ERROR_CODE	VARCHAR(3),
    ERROR_CAUSE	VARCHAR(512),
    DATA	TEXT,
    CONSTRAINT VERIFICATION_HIST_PK PRIMARY KEY (SEQ)

);


-- 2022-03-05
CREATE TABLE INGEST_INTERFACE.JSONLD_CONTEXT_BASE
(
    URL                  VARCHAR(1024) NOT NULL,
    PAYLOAD              TEXT  NOT NULL,
    REFINED_PAYLOAD         TEXT NOT NULL,
    KIND                 VARCHAR(20) NOT NULL,
    EXPIRE_DATETIME      TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATE_DATETIME      TIMESTAMP WITH TIME ZONE,
    MODIFY_DATETIME      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT JSONLD_CONTEXT_BASE_PK PRIMARY KEY (URL)
);

-- 2022-05-08
ALTER TABLE INGEST_INTERFACE.ACL_RULE ADD COLUMN OPERATION VARCHAR(16)[] DEFAULT '{"create", "update", "retrieve", "delete"}' NOT NULL;

-- 2022-06-11
ALTER TABLE INGEST_INTERFACE.ACL_RULE ALTER COLUMN CONDITION DROP NOT NULL;