spring:
  application:
    name: dh-datacore-ui

  thymeleaf:
    prefix: classpath:/static/
    cache: false

  security:
    enabled: false

  # only dev
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

server:
  port: 8083

  servlet:
    context-path: /
    session.timeout: 60m

  timezone: Asia/Seoul

# Logging
logging.config: classpath:logback-spring.xml
logging.base.dir: logs

# Language (en: English, ko: Korean)
language.code: ko

# DB Connection
datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://10.12.0.11:5432/datacore
  username: keti_datacore
  password: keti123

  secondary:
    use.yn: Y
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.12.0.11:5432/datacore
    username: keti_datacore
    password: keti123

# HTTP retrieve
datacore:
  http:
    binding:
      response:
        log.yn: Y
      cause:
        msg:
          trace:
            key: x-detail-error-key
            value: BBBBB
          level: 3

datamanager:
  url: http://10.12.0.5:8080

ingestinterface:
  url: http://10.12.0.12:8080
  
cityhub:
  client:
    clientId: FGppHOCNp8LC69pZnjSN
    clientSecret: fV83KX75CRXJNTF81F7QWHuG0OFhfh5u
    userAuthorizationUri: http://203.253.128.181:30084/oauth2.0/authorize
    accessTokenUri: http://10.7.0.22:30000/oauth2.0/token
    publicKeyUri: http://10.7.0.22:30000/security/publickey
    logoutUri: http://10.7.0.22:30000/security/logout
    userInfoUri: http://10.7.0.22:30000/security/users
    redirectUri: http://203.253.128.181:16608/accesstoken

# Eureka (enabled: set false to turn off dev)
eureka: 
  instance: 
    prefer-ip-address: true

  client: 
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://133.186.162.81:8888/eureka, http://133.186.162.82:8888/eureka, http://133.186.162.83:8888/eureka

http.pool: 
  max.total: 200
  defaultMaxPerRoute: 100
  connection.timeout: 5000
  connection.request.timeout: 5000 
  read.timeout: 10000 
  validate.after.inactivity: 2000
