CREATE SCHEMA DATA_SERVICE_BROKER
    AUTHORIZATION POSTGRES;

CREATE TABLE DATA_SERVICE_BROKER.DATA_MODEL_BASE
(
    NAMESPACE       VARCHAR(256),
    TYPE            VARCHAR(64),
    VERSION         VARCHAR(10),
    NAME            VARCHAR(100),
    DESCRIPTION     VARCHAR(500),
    DATA_MODEL      TEXT                     NOT NULL,
    DDL             TEXT                     NOT NULL,
    ENABLED         BOOLEAN DEFAULT TRUE,
    CREATE_DATETIME TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITH TIME ZONE,
    MODIFIER_ID     VARCHAR(64),
    CONSTRAINT DATA_MODEL_BASE_PK PRIMARY KEY (NAMESPACE, TYPE, VERSION)
);


CREATE TABLE DATA_SERVICE_BROKER.DATASET_BASE
(
    ID                    VARCHAR(256) NOT NULL,
    NAME                  VARCHAR(256),
    DESCRIPTION           VARCHAR(512),
    UPDATE_INTERVAL       VARCHAR(50),
    CATEGORY              VARCHAR(4),
    PROVIDER_ORGANIZATION VARCHAR(256),
    PROVIDER_SYSTEM       VARCHAR(256),
    IS_PROCESSED          VARCHAR(256),
    OWNERSHIP             VARCHAR(32),
    KEYWORD               VARCHAR(4)[],
    LICENSE               VARCHAR(4),
    PROVIDING_API_URI     VARCHAR(512),
    RESTRICTIONS          VARCHAR(512),
    DATASET_EXTENSION     VARCHAR(16),
    DATASET_ITEMS         VARCHAR(512),
    TARGET_REGIONS        VARCHAR(512),
    SOURCE_DATASET_IDS    VARCHAR(512)[],
    DATA_STORE_URI        VARCHAR(1024)[],
    QUALITY_CHECK_ENABLED BOOLEAN,
    DATA_IDENTIFIER_TYPE  VARCHAR(64),
    DATAMODEL_TYPE        VARCHAR(64),
    DATAMODEL_NAMESPACE   VARCHAR(256),
    DATAMODEL_VERSION     VARCHAR(10),
    ENABLED               BOOLEAN      NOT NULL DEFAULT TRUE,
    STORAGE_RETENTION     INTEGER,
    TOPIC_RETENTION       BIGINT,
    CREATE_DATETIME       TIMESTAMP WITH TIME ZONE,
    CREATOR_ID            VARCHAR(64),
    MODIFY_DATETIME       TIMESTAMP WITH TIME ZONE,
    MODIFIER_ID           VARCHAR(64),
    CONSTRAINT DATA_SET_BASE_PK PRIMARY KEY (ID)
);


CREATE TABLE DATA_SERVICE_BROKER.DATASET_FLOW_BASE
(
    DATASET_ID         VARCHAR(64)                            NOT NULL,
    DESCRIPTION        VARCHAR(512),
    HISTORY_STORE_TYPE VARCHAR(20)                            NOT NULL,
    ENABLED            BOOLEAN                  DEFAULT 't'   NOT NULL,
    CREATE_DATETIME    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID         VARCHAR(64),
    MODIFY_DATETIME    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID        VARCHAR(64),
    CONSTRAINT DATASET_FLOW_BASE_PK PRIMARY KEY (DATASET_ID)
);


CREATE TABLE DATA_SERVICE_BROKER.SUBSCRIPTION_BASE
(
    ID                             VARCHAR(256) NOT NULL,
    NAME                           VARCHAR(256),
    TYPE                           VARCHAR(50),
    DESCRIPTION                    VARCHAR(500),
    WATCHED_ATTRIBUTES             VARCHAR(256)[],
    TIME_INTERVAL                  NUMERIC(16),
    Q                              VARCHAR(4000),
    GEO_Q                          TEXT,
    CSF                            VARCHAR(500),
    IS_ACTIVE                      VARCHAR(5),
    NOTIFICATION_ATTRIBUTES        VARCHAR(256)[],
    NOTIFICATION_FORMAT            VARCHAR(10),
    NOTIFICATION_ENDPOINT_URI      VARCHAR(500) NOT NULL,
    NOTIFICATION_ENDPOINT_ACCEPT   VARCHAR(50),
    NOTIFICATION_STATUS            VARCHAR(6),
    NOTIFICATION_TIME_SENT         NUMERIC(16),
    NOTIFICATION_LAST_NOTIFICATION timestamp WITH time zone,
    NOTIFICATION_LAST_FAILURE      timestamp WITH time zone,
    NOTIFICATION_LAST_SUCCESS      timestamp WITH time zone,
    EXPIRE                         timestamp WITH time zone,
    THROTTLING                     NUMERIC(16),
    TEMPORAL_Q_TIMEREL             VARCHAR(8),
    TEMPORAL_Q_TIME                timestamp WITH time zone,
    TEMPORAL_Q_END_TIME            timestamp WITH time zone,
    TEMPORAL_Q_TIME_PROPERTY       VARCHAR(50),
    STATUS                         VARCHAR(8),
    CREATE_DATETIME                timestamp WITH time zone,
    CREATOR_ID                     VARCHAR(64),
    MODIFY_DATETIME                timestamp WITH time zone,
    MODIFIER_ID                    VARCHAR(64),
    CONSTRAINT SUBSCRIPTION_BASE_PK PRIMARY KEY (ID)
);

CREATE TABLE DATA_SERVICE_BROKER.SUBSCRIPTION_ENTITIES
(
    ID              VARCHAR(256),
    SUBSCRIPTION_ID VARCHAR(256) NOT NULL,
    ID_PATTERN      VARCHAR(256),
    TYPE            VARCHAR(100) NOT NULL,
    CONSTRAINT SUBSCRIPTION_ENTITIES_FK01 FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES DATA_SERVICE_BROKER.SUBSCRIPTION_BASE (ID)
);


CREATE TABLE DATA_SERVICE_BROKER.ENTITY_DATA_MODEL_BASE
(
    ID                   VARCHAR(256) NOT NULL,
    DATASET_ID           VARCHAR(256) NOT NULL,
    DATA_MODEL_NAMESPACE VARCHAR(256) NOT NULL,
    DATA_MODEL_TYPE      VARCHAR(64)  NOT NULL,
    DATA_MODEL_VERSION   VARCHAR(10)  NOT NULL,
    CREATE_DATETIME      TIMESTAMP WITH TIME ZONE,
    MODIFY_DATETIME      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ENTITY_BASE_PK PRIMARY KEY (ID)
);


CREATE TABLE DATA_SERVICE_BROKER.CSOURCE_REGISTRATION_BASE
(
    ID                         VARCHAR(256) NOT NULL,
    TYPE                       VARCHAR(100),
    NAME                       VARCHAR(256),
    DESCRIPTION                VARCHAR(500),
    OBSERVATION_INTERVAL_START TIMESTAMP WITHOUT TIME ZONE,
    OBSERVATION_INTERVAL_END   TIMESTAMP WITHOUT TIME ZONE,
    MANAGEMENT_INTERVAL_START  TIMESTAMP WITHOUT TIME ZONE,
    MANAGEMENT_INTERVAL_END    TIMESTAMP WITHOUT TIME ZONE,
    LOCATION                   GEOMETRY,
    OBSERVATION_SPACE          GEOMETRY,
    EXPIRES                    TIMESTAMP WITHOUT TIME ZONE,
    ENDPOINT                   VARCHAR(256),
    CONTEXT                    VARCHAR(256)[],
    OPERATION_SPACE            GEOMETRY,
    CONSTRAINT CSOURCE_REGISTRATION_BASE_PK PRIMARY KEY (ID)
);

CREATE TABLE DATA_SERVICE_BROKER.CSOURCE_REGISTRATION_INFO
(
    CSOURCE_REGISTRATION_INFO_ID VARCHAR(256),
    CSOURCE_REGISTRATION_BASE_ID VARCHAR(256),
    PROPERTIES                   VARCHAR(50)[],
    RELATIONSHIPS                VARCHAR(50)[],
    MODIFIED_AT                  TIMESTAMP WITHOUT TIME ZONE
);


CREATE TABLE DATA_SERVICE_BROKER.CSOURCE_REGISTRATION_ENTITY
(
    CSOURCE_REGISTRATION_BASE_ID VARCHAR(256),
    CSOURCE_REGISTRATION_INFO_ID VARCHAR(256),
    ENTITY_ID                    VARCHAR(256),
    ENTITY_ID_PATTERN            VARCHAR(256),
    ENTITY_TYPE                  VARCHAR(100)
);

-- 2020-12-27
ALTER TABLE DATA_SERVICE_BROKER.DATASET_FLOW_BASE ADD COLUMN BIG_DATA_STORAGE_TYPES VARCHAR(30);
ALTER TABLE DATA_SERVICE_BROKER.DATA_MODEL_BASE ALTER COLUMN DDL DROP NOT NULL;

-- 2020-01-09
ALTER TABLE DATA_SERVICE_BROKER.DATA_MODEL_BASE ADD COLUMN PROVISIONING_ID VARCHAR(64);
ALTER TABLE DATA_SERVICE_BROKER.DATA_MODEL_BASE ADD COLUMN PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE;

ALTER TABLE DATA_SERVICE_BROKER.DATASET_BASE ADD COLUMN PROVISIONING_ID VARCHAR(64);
ALTER TABLE DATA_SERVICE_BROKER.DATASET_BASE ADD COLUMN PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE;
    
ALTER TABLE DATA_SERVICE_BROKER.DATASET_FLOW_BASE ADD COLUMN PROVISIONING_ID VARCHAR(64);
ALTER TABLE DATA_SERVICE_BROKER.DATASET_FLOW_BASE ADD COLUMN PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE;


-- 2020-03-19
ALTER TABLE DATA_SERVICE_BROKER.DATASET_BASE ALTER COLUMN DATASET_EXTENSION TYPE VARCHAR(256);
ALTER TABLE DATA_SERVICE_BROKER.DATASET_BASE ALTER COLUMN LICENSE TYPE VARCHAR(256);
ALTER TABLE DATA_SERVICE_BROKER.DATASET_BASE ALTER COLUMN KEYWORD TYPE VARCHAR(256)[];
ALTER TABLE DATA_SERVICE_BROKER.DATASET_BASE ALTER COLUMN CATEGORY TYPE VARCHAR(256);
ALTER TABLE DATA_SERVICE_BROKER.DATASET_BASE ALTER COLUMN DATA_IDENTIFIER_TYPE TYPE VARCHAR(256);


-- 2020-03-21
ALTER TABLE DATA_SERVICE_BROKER.ENTITY_DATA_MODEL_BASE ALTER COLUMN DATASET_ID DROP NOT NULL;

-- 2021-06-27
ALTER TABLE DATA_SERVICE_BROKER.SUBSCRIPTION_BASE ADD COLUMN NOTIFICATION_ENDPOINT_NOTIFIER_INFO VARCHAR(1024);
ALTER TABLE DATA_SERVICE_BROKER.SUBSCRIPTION_BASE ADD COLUMN NOTIFICATION_ENDPOINT_RECEIVER_INFO VARCHAR(1024);

-- 2021-07-03 접근제어
CREATE TABLE DATA_SERVICE_BROKER.ACL_RULE
(
    ID                    VARCHAR(40) NOT NULL,
    USER_ID               VARCHAR(50),
    CLIENT_ID             VARCHAR(50),
    DATASET_ID            VARCHAR(256),
    CONDITION             VARCHAR(10) NOT NULL,
    CREATE_DATETIME       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID            VARCHAR(64),
    MODIFY_DATETIME       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID           VARCHAR(64),
    PROVISIONING_ID       VARCHAR(64),
    PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ACL_RULE_PKEY PRIMARY KEY (ID)
);

ALTER TABLE DATA_SERVICE_BROKER.ACL_RULE RENAME DATASET_ID TO RESOURCE_ID;
ALTER TABLE DATA_SERVICE_BROKER.ACL_RULE ADD COLUMN RESOURCE_TYPE VARCHAR (10) ;




CREATE TABLE DATA_SERVICE_BROKER.SERVICE_REGISTRATION_BASE
(
    ID            VARCHAR(256),
    TYPE        VARCHAR(64),
    NAME        VARCHAR(100),
    DESCRIPTION        VARCHAR(500),
    INFORMATION        TEXT    NOT NULL,
    CREATE_DATETIME    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID        VARCHAR(64),
    MODIFY_DATETIME     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID         VARCHAR(64),
    CONSTRAINT SERVICE_REGISTRATION_BASE_PK PRIMARY KEY (ID)
);


CREATE TABLE DATA_SERVICE_BROKER.SERVICE_EXECUTION_BASE
(
    ID            VARCHAR(256),
    SERVICE_ID        VARCHAR(256),
    TYPE        VARCHAR(64),
    CREATE_DATETIME    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID        VARCHAR(64),
    MODIFY_DATETIME     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID         VARCHAR(64),
    CONSTRAINT SERVICE_EXECUTION_BASE_PK PRIMARY KEY (ID, SERVICE_ID)
);

CREATE TABLE DATA_SERVICE_BROKER.SERVICE_EXECUTION_DETAIL
(
    ID            VARCHAR(256),
    SERVICE_ID        VARCHAR(256),
    EXECUTION_ID    VARCHAR(256),
    NAME        VARCHAR(256),
    ENTITY_ID        VARCHAR(256),
    ENTITY_TYPE        VARCHAR(64),
    TYPE        VARCHAR(64),
    INPUT        TEXT,
    STATUS        VARCHAR(20),
    CREATE_DATETIME    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID        VARCHAR(64),
    MODIFY_DATETIME     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID         VARCHAR(64),
    CONSTRAINT SERVICE_EXECUTION_DETAIL_PK PRIMARY KEY (ID, SERVICE_ID, EXECUTION_ID)
);

-- 2020-07-25
-- DATA_MODEL_BASE 테이블 DROP 후 신규 CREATE (PK 바뀜)
-- DATASET_BASE 테이블 DROP 후 신규 CREATE (데이터모델 PK 바뀜)
-- ENTITY_DATA_MODEL_BASE 테이블 DROP 후 신규 CREATE (데이터모델 PK 바뀜)

DROP TABLE DATA_SERVICE_BROKER.DATASET_BASE;
DROP TABLE DATA_SERVICE_BROKER.DATA_MODEL_BASE;
DROP TABLE DATA_SERVICE_BROKER.ENTITY_DATA_MODEL_BASE;

CREATE TABLE DATA_SERVICE_BROKER.DATA_MODEL_BASE
(
    ID		    VARCHAR(1024),
    TYPE            VARCHAR(64)	  NOT NULL,
    TYPE_URI        VARCHAR(1024) NOT NULL,
    NAME            VARCHAR(100),
    DESCRIPTION     VARCHAR(500),
    DATA_MODEL      TEXT                     NOT NULL,
    ENABLED         BOOLEAN DEFAULT TRUE,
    CREATE_DATETIME TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITH TIME ZONE,
    MODIFIER_ID     VARCHAR(64),
    PROVISIONING_ID VARCHAR(64),
    PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE,
    CONSTRAINT DATA_MODEL_BASE_PK PRIMARY KEY (ID),
    CONSTRAINT DATA_MODEL_BASE_UK01 UNIQUE (TYPE_URI)
);


CREATE TABLE DATA_SERVICE_BROKER.DATASET_BASE
(
    ID                    VARCHAR(256) NOT NULL,
    NAME                  VARCHAR(256),
    DESCRIPTION           VARCHAR(512),
    UPDATE_INTERVAL       VARCHAR(50),
    CATEGORY              VARCHAR(256),
    PROVIDER_ORGANIZATION VARCHAR(256),
    PROVIDER_SYSTEM       VARCHAR(256),
    IS_PROCESSED          VARCHAR(256),
    OWNERSHIP             VARCHAR(32),
    KEYWORD               VARCHAR(256)[],
    LICENSE               VARCHAR(256),
    PROVIDING_API_URI     VARCHAR(512),
    RESTRICTIONS          VARCHAR(512),
    DATASET_EXTENSION     VARCHAR(256),
    DATASET_ITEMS         VARCHAR(512),
    TARGET_REGIONS        VARCHAR(512),
    SOURCE_DATASET_IDS    VARCHAR(512)[],
    DATA_STORE_URI        VARCHAR(1024)[],
    QUALITY_CHECK_ENABLED BOOLEAN,
    DATA_IDENTIFIER_TYPE  VARCHAR(256),
    DATAMODEL_ID          VARCHAR(1024),
    ENABLED               BOOLEAN      NOT NULL DEFAULT TRUE,
    STORAGE_RETENTION     INTEGER,
    TOPIC_RETENTION       BIGINT,
    CREATE_DATETIME       TIMESTAMP WITH TIME ZONE,
    CREATOR_ID            VARCHAR(64),
    MODIFY_DATETIME       TIMESTAMP WITH TIME ZONE,
    MODIFIER_ID           VARCHAR(64),
    PROVISIONING_ID	  VARCHAR(64),
    PROVISIONING_DATETIME TIMESTAMP WITH TIME ZONE,
    CONSTRAINT DATA_SET_BASE_PK PRIMARY KEY (ID)
);


CREATE TABLE DATA_SERVICE_BROKER.ENTITY_DATA_MODEL_BASE
(
    ID                   VARCHAR(256) NOT NULL,
    DATASET_ID           VARCHAR(256),
    DATA_MODEL_ID	 VARCHAR(1024) NOT NULL,
    DATA_MODEL_TYPE      VARCHAR(64)  NOT NULL,
    CREATE_DATETIME      TIMESTAMP WITH TIME ZONE,
    MODIFY_DATETIME      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ENTITY_BASE_PK PRIMARY KEY (ID)
);

-- 2021-08-08
ALTER TABLE DATA_SERVICE_BROKER.SUBSCRIPTION_ENTITIES ADD COLUMN TYPE_URI VARCHAR(1024);

-- 2021-08-21
ALTER TABLE DATA_SERVICE_BROKER.SUBSCRIPTION_BASE ADD COLUMN DATASET_IDS VARCHAR(512)[];

-- 2021-09-07
ALTER TABLE DATA_SERVICE_BROKER.DATA_MODEL_BASE ADD COLUMN CREATED_STORAGE_TYPES VARCHAR(128)[];

-- 2021-09-24
ALTER TABLE DATA_SERVICE_BROKER.DATA_MODEL_BASE ADD COLUMN STORAGE_METADATA TEXT;

-- 2021-11-15
ALTER TABLE DATA_SERVICE_BROKER.SUBSCRIPTION_BASE ADD COLUMN CONTEXT VARCHAR(4000)[];

-- 2021-11-20
ALTER TABLE DATA_SERVICE_BROKER.CSOURCE_REGISTRATION_BASE ADD COLUMN SUPPORTED_AGGREGATION_METHOD VARCHAR(50)[];
ALTER TABLE DATA_SERVICE_BROKER.CSOURCE_REGISTRATION_BASE ADD COLUMN SCOPE VARCHAR(50)[];
ALTER TABLE DATA_SERVICE_BROKER.CSOURCE_REGISTRATION_BASE ADD COLUMN SCOPE_DATA_TYPE VARCHAR(20);

-- 2022-03-05
CREATE TABLE DATA_SERVICE_BROKER.JSONLD_CONTEXT_BASE
(
    URL                  VARCHAR(1024) NOT NULL,
    PAYLOAD              TEXT  NOT NULL,
    REFINED_PAYLOAD	     TEXT NOT NULL,
    KIND        	     VARCHAR(20) NOT NULL,
    EXPIRE_DATETIME      TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATE_DATETIME      TIMESTAMP WITH TIME ZONE,
    MODIFY_DATETIME      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT JSONLD_CONTEXT_BASE_PK PRIMARY KEY (URL)
);

-- 2022-05-08
ALTER TABLE DATA_SERVICE_BROKER.ACL_RULE ADD COLUMN OPERATION VARCHAR(16)[] DEFAULT '{"create", "update", "retrieve", "delete"}' NOT NULL;

-- 2022-06-11
ALTER TABLE DATA_SERVICE_BROKER.ACL_RULE ALTER COLUMN CONDITION DROP NOT NULL;